### ISSUE TITLE
Final Project Feedback

### ISSUE THREAD

**Issue by abakus00** [marcogianni/blockchain-developer-bootcamp-final-project#1]
Hi @marcogianni,
Please include your public Ethereum account if you would like to receive your certification as an NFT (this is optional).

**Comment by marcogianni** [comment]
Hi @abakus00, just added in the `hardhat-project` readme. 
Is there a version of the certificate for Linkedin?

**Comment by abakus00** [comment]
Great! Not sure about LinkedIn
